---

- hosts: localhost
  pre_tasks:
    - name: GPG keys
      import_role:
        name: user/gpg
      vars:
        gpg: "{{ user['gpg_keys'] }}"
      when:
        - user is defined
        - user.gpg_keys is defined
 
  roles:
    - role: user/git
      vars:
        settings:
          user:
            name: "{{ user['name'] }}"
            email: " {{ user['email'] }}"
    - user/dev/python
  
  become: no
  environment: "{{ proxy_env if proxy_env is defined else '' }}"
