---

- hosts: localhost
  roles:
    - role: user/latex
      vars:
        package: 'extra'
        extensions:
          - extra-utils
        editors:
          - texstudio
          - gummi

  become: no
  environment: "{{ proxy_env if proxy_env is defined else '' }}"
