---

- hosts: localhost
  roles:
    - role: user/shell
      vars:
        bash:
          alias:
            ll: 'ls -alF'
            la: 'ls -A'
            l: 'ls -CF'
          history:
            size: 10000
            filesize: 10000
            timeformat: '"%Y-%m-%d %H:%M:%S:   "'
          shopt:
            cdspell: yes
            cmdhist: yes
            dotglob: yes
          set:
            notify: yes
            pipefail: yes
  become: no
  environment: "{{ proxy_env if proxy_env is defined else '' }}"
