---

- hosts: localhost
  roles:
    - role: user/vim
      vars:
        flavor: vim
    - role: user/vim
      vars:
        flavor: neovim
        
  vars:
    plugin_manager: vundle
    settings:
      set:
        value:
          encoding: utf-8
          termencoding: utf-8
          updatetime: 200
          history: 1000
          undolevels: 1000
          mouse: a
          wildmode: 'longest,list'
          backspace: 'indent,eol,start'
          tabstop: 4
          shiftwidth: 4
        property:
          - expandtab
          - incsearch
          - hlsearch
          - number
          - hidden
          - autoread
          - ttyfast
      other:
        - 'colorscheme elflord'
        - 'syntax on'
    
    plugins:
      - name: 'Valloric/YouCompleteMe'
        set:
          value:
            encoding: 'utf-8'
      - name: 'nathanaelkane/vim-indent-guides'
      - name: 'airblade/vim-gitgutter'
      - name: 'editorconfig/editorconfig-vim'
        let:
          'g:EditorConfig_exclude_patterns': "['scp://.*']"
      - name: 'itchyny/lightline.vim'
        set:
          value:
            laststatus: 2
            showtabline: 2         
        other:
          - 'set guioptions-=e'
      - name: 'vim-syntastic/syntastic'
        other:
          - 'set statusline+=%#warningmsg#'
          - 'set statusline+=%{SyntasticStatuslineFlag()}'
          - 'set statusline+=%*'
        let:
          'g:syntastic_always_populate_loc_list': 1
          'g:syntastic_auto_loc_list': 1
          'g:syntastic_check_on_open': 1
          'g:syntastic_check_on_wq': 0
          'g:syntastic_python_pylint_exe': "'python3 -m pylint3'"
      - name: 'flazz/vim-colorschemes'
      - name: 'junegunn/fzf.vim'
      - name: 'scrooloose/nerdtree'
        let:
          NERDTreeMapActivateNode: "'<right>'"
          NERDTreeShowHidden: 1
        other:
          - 'nmap <leader>n :NERDTreeToggle<CR>'
      - name: 'terryma/vim-multiple-cursors'
      - name: 'tpope/vim-eunuch'
      - name: 'tpope/vim-surround'
      - name: 'w0rp/ale'
      - name: 'ludovicchabant/vim-lawrencium'
  become: no
  environment: "{{ proxy_env if proxy_env is defined else '' }}"
