---

# inspired by:
# 1. http://stevelosh.com/blog/2010/09/coming-home-to-vim/#vim-s-feeling
# 2. https://github.com/nvie/vimrc/blob/master/vimrc
# 3. https://github.com/junegunn/dotfiles/blob/master/vimrc
# 4. https://github.com/davidhalter/dotfiles/blob/master/.vimrc
# 5. https://github.com/jessfraz/.vim
# 6. https://github.com/humiaozuzu/dot-vimrc
# 7. https://github.com/akrawchyk/awesome-vim
# 8. https://github.com/arusahni/dotfiles/blob/45c6655d46d1f672cc36f4e81c2a674484739ebc/vimrc#L42
# 9. https://github.com/amix/vimrc
# 10. http://marcgg.com/blog/2016/03/01/vimrc-example/
# 11. https://dougblack.io/words/a-good-vimrc.html
# 12. https://github.com/vgod/vimrc

- hosts: localhost
  roles:
    - role: user/vim
      vars:
        flavor: vim
    - role: user/vim
      vars:
        flavor: neovim
        
  vars:
    plugin_manager: vundle
    settings:
      set:
        value:
          viminfo: ""
          shell: bash
          encoding: utf-8                      
          termencoding: utf-8
          clipboard: unnamed
          updatetime: 200
          history: 1000
          undolevels: 1000
          mouse: a              # enable using the mouse
          scrolloff: 3
          wildmode: 'longest,list'
          wildignore: '*.swp,*.bak,*.pyc,*.class'
          backspace: 'indent,eol,start'
          tabstop: 4
          shiftwidth: 4
          scrolloff: 10         # scroll on search so that at least N lines are above and below the current line
        property:
          - expandtab
          - incsearch           # search incrementally as being typed
          - hlsearch            # highlight search results
          - smartcase           # ignore case if search pattern is all lowercase, case-sensitive otherwise
          - showmatch           # show matching parenthesis 
          - number              # show line numbers
          - hidden
          - autoread            # automatically read file changes
          - ttyfast             # fast keyboard input
          - wrap                # wrap lines only visually (do not enter \n)
          - linebreak           # break only on special characters set in the 'breakat' option (" ^I!@*-+;:,./?")
          - noswapfile
          - title
      let:
        'mapleader': '","'
      other:
        - 'colorscheme elflord'
        - 'syntax on'
        - 'nnoremap / /\v'      # insert \v before any searched string to use non-vim regex
        - 'vnoremap / /\v'      # insert \v before any searched string to use non-vim regex
        - 'nnoremap <leader><space> :noh<cr>'   # clear screen after search
        - 'au FocusLost * :wa'  # save on losing focus
        - 'nnoremap j gj'       # map j to act as expected on long, wrapped lines
        - 'nnoremap k gk'       # map k to act as expected on long, wrapped lines

    plugins:
      - name: 'Valloric/YouCompleteMe'
        set:
          value:
            encoding: 'utf-8'
      - name: 'nathanaelkane/vim-indent-guides'
      - name: 'airblade/vim-gitgutter'
      - name: 'editorconfig/editorconfig-vim'
        let:
          'g:EditorConfig_exclude_patterns': "['scp://.*']"
      - name: 'itchyny/lightline.vim'
        set:
          value:
            laststatus: 2
            showtabline: 2         
        other:
          - 'set guioptions-=e'
      - name: 'vim-syntastic/syntastic'
        other:
          - 'set statusline+=%#warningmsg#'
          - 'set statusline+=%{SyntasticStatuslineFlag()}'
          - 'set statusline+=%*'
        let:
          'g:syntastic_always_populate_loc_list': 1
          'g:syntastic_auto_loc_list': 1
          'g:syntastic_check_on_open': 1
          'g:syntastic_check_on_wq': 0
          'g:syntastic_python_pylint_exe': "'python3 -m pylint3'"
      - name: 'flazz/vim-colorschemes'
      - name: 'junegunn/fzf.vim'
      - name: 'scrooloose/nerdtree'
        let:
          NERDTreeMapActivateNode: "'<right>'"
          NERDTreeShowHidden: 1
        other:
          - 'nmap <leader>n :NERDTreeToggle<CR>'
      - name: 'scrooloose/nerdcommenter'
        let:
          'g:NERDSpaceDelims': 1
          'g:NERDCommentEmptyLines': 1
          'g:NERDTrimTrailingWhitespace': 1
          'g:NERDToggleCheckAllLines': 1
      - name: 'terryma/vim-multiple-cursors'
      - name: 'tpope/vim-eunuch'
      - name: 'tpope/vim-surround'
      - name: 'w0rp/ale'
      - name: 'ludovicchabant/vim-lawrencium'
  become: no
  environment: "{{ proxy_env if proxy_env is defined else '' }}"
