---

# bashrc inspired by:
# 1. https://medium.com/@waxzce/use-bashrc-d-directory-instead-of-bloated-bashrc-50204d5389ff
# 2. https://github.com/junegunn/dotfiles
# 3. https://gist.github.com/torifat/1254570
# 4. https://github.com/nacitar/bashrc
# 5. https://gist.github.com/illucent/8132033
# 6. https://gist.github.com/redguardtoo/01868d7a13817c9845e8#file-bashrc-L96
# 7. https://github.com/paulmooring/bashrc
# 8. https://github.com/SuRaMoN/bashrc
# 9. https://github.com/twolfson/sexy-bash-prompt
# 10. https://github.com/gurjeet/home/blob/master/.bashrc

- hosts: localhost
  become: no
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: user/shell
      vars:
        bash:
          alias:
            ll: 'ls -alF'
            la: 'ls -A'
            l: 'ls -CF'
          history:
            size: 10000
            filesize: 10000
            timeformat: '"%Y-%m-%d %H:%M:%S:   "'
          shopt:
            cdspell: yes
            cmdhist: yes
            dotglob: yes
          set:
            notify: yes
            pipefail: yes

