---

# inspired by:
# 1. http://stevelosh.com/blog/2010/09/coming-home-to-vim/#vim-s-feeling
# 2. https://github.com/nvie/vimrc/blob/master/vimrc
# 3. https://github.com/junegunn/dotfiles/blob/master/vimrc
# 4. https://github.com/davidhalter/dotfiles/blob/master/.vimrc
# 5. https://github.com/jessfraz/.vim
# 6. https://github.com/humiaozuzu/dot-vimrc
# 7. https://github.com/akrawchyk/awesome-vim
# 8. https://github.com/arusahni/dotfiles/blob/45c6655d46d1f672cc36f4e81c2a674484739ebc/vimrc#L42
# 9. https://github.com/amix/vimrc
# 10. http://marcgg.com/blog/2016/03/01/vimrc-example/
# 11. https://dougblack.io/words/a-good-vimrc.html
# 12. https://github.com/vgod/vimrc

- hosts: localhost
  become: no
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: user/vim
      vars:
        flavor: vim
        
  vars:
    configuration:
      - name: basic configuration
        block: |
          set viminfo=
          set updatetime=200
          set shell=bash
          set undolevels=1000
          set encoding=utf-8
          set wildignore=*.swp,*.bak,*.pyc,*.class
          set tabstop=4
          set backspace=indent,eol,start
          set wildmode=longest,list
          set shiftwidth=4
          set scrolloff=10            " scroll on search so that at least N lines are above and below the current line
          set mouse=a                 " enable using the mouse
          set termencoding=utf-8
          set history=1000
          set expandtab
          set incsearch               " search incrementally as being typed
          set hlsearch                " highlight search results
          set smartcase               " ignore case if search pattern is all lowercase, case-sensitive otherwise
          set showmatch               " show matching parenthesis
          set number                  " show line numbers
          set relativenumber          " line numbers relative to the current line
          set hidden
          set autoread                " automatically read file changes
          set ttyfast                 " fast keyboard input
          set wrap                    " wrap lines only visually
          set linebreak               " break only on special characters set in the 'breakat' option (" ^I!@*-+;:,./?")
          set noswapfile
          set title
          let mapleader=","
          colorscheme elflord
          syntax on

      - name: insert \v before any searched string to use non-vim regex
        block: |
          nnoremap / /\v
          vnoremap / /\v

      - name: clear screen after search
        block: |
          nnoremap <leader><space> :noh<cr>

      - name: misc
        block: |
          au FocusLost * :wa
          nnoremap j gj
          nnoremap k gk

      - name: bindings | YAML
        block: |
          au! BufNewFile,BufReadPost *.{yaml,yml} set filetype=yaml
          autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab

    plugins:
      - name: 'Valloric/YouCompleteMe'
        setttings: |
          set encoding=utf-8
      - name: 'nathanaelkane/vim-indent-guides'
      - name: 'airblade/vim-gitgutter'
      - name: 'editorconfig/editorconfig-vim'
        settings: |
          let g:EditorConfig_exclude_patterns=['scp://.*']
      - name: 'itchyny/lightline.vim'
        settings: |
          set showtabline=2
          set guioptions-=e
      - name: 'vim-syntastic/syntastic'
        settings: |
          let g:syntastic_always_populate_loc_list=1
          let g:syntastic_check_on_open=1
          let g:syntastic_auto_loc_list=1
          let g:syntastic_python_pylint_exe='python3 -m pylint3'
          let g:syntastic_check_on_wq=0
          set statusline+=%#warningmsg#
          set statusline+=%{SyntasticStatuslineFlag()}
          set statusline+=%*
      - name: 'flazz/vim-colorschemes'
      - name: 'junegunn/fzf.vim'
      - name: 'mrk21/yaml-vim'
      - name: 'scrooloose/nerdtree'
        settings: |
          let NERDTreeShowHidden=1
          let NERDTreeMapActivateNode='<right>'
          
          nmap <leader>n :NERDTreeToggle<CR>
      - name: 'scrooloose/nerdcommenter'
        settings: |
          let g:NERDToggleCheckAllLines=1
          let g:NERDCommentEmptyLines=1
          let g:NERDSpaceDelims=1
          let g:NERDTrimTrailingWhitespace=1
      - name: 'terryma/vim-multiple-cursors'
      - name: 'tpope/vim-eunuch'
      - name: 'tpope/vim-surround'
      - name: 'w0rp/ale'
      - name: 'ludovicchabant/vim-lawrencium'
      - name: 'vim-scripts/vim-auto-save'
        settings: |
          let g:auto_save=1
          let g:auto_save_silent=1
          let g:auto_save_in_insert_mode=0
          let g:auto_save_no_updatetime=1
